INSERT INTO CLIENTE(APE_MATERNO, APE_PATERNO, DIRECCION, EMAIL, NOMBRE, TELEFONO)VALUES('RETUERTO', 'BARRIENTOS', 'LOS CLAVELES 223',  'EBARRIENTOS@GMAIL.COM', 'EDWIN', '99966655');
INSERT INTO CLIENTE(APE_MATERNO, APE_PATERNO, DIRECCION, EMAIL, NOMBRE, TELEFONO)VALUES('LOPEZ', 'GUTIERREZ', 'LOS SAUCES 223',  'LGUTIERREZ@GMAIL.COM', 'JUAN', '054547454');
INSERT INTO CLIENTE(APE_MATERNO, APE_PATERNO, DIRECCION, EMAIL, NOMBRE, TELEFONO)VALUES('SIFUENTES', 'MALDONADO', 'LOS ROBLES 223',  'SMALDONADO@GMAIL.COM', 'EUDOCIO', '4454545');
INSERT INTO CLIENTE(APE_MATERNO, APE_PATERNO, DIRECCION, EMAIL, NOMBRE, TELEFONO)VALUES('CORONEL', 'DOMINGUEZ', 'CALLE PRINCIPAL 223',  'DESCONOCIDO@GMAIL.COM', 'LUCAS', '54654654');


INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'NOMBRE', 'text', 'JUAN');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'APELLIDO', 'text', 'LOPEZ');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'DIRECCION', 'text', 'LAS LOMAS');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'TELEFONO', 'text', '55555555');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'SEXO', 'boolean', 'true');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(1,'ESTATURA', 'number', '1.63');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(2,'NOMBRE', 'text', 'PEDRO');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(2,'UNIVERSIDAD', 'text', 'UNS');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(2,'GRADO', 'text', 'TITULADO');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(2,'EXPERIENCIA', 'number', '5');
INSERT INTO FORMULARIO(ID_FORMULARIO, LABEL, TIPO, VALOR)VALUES(2,'F. CREACION', 'date', '');
